-- Add recurring Taco Tuesday and Trivia Night events from August 2025 through November 18, 2025

-- Taco Tuesday events (all-day events)
INSERT INTO public.events (event_title, event_date, event_type, description, location, status, allow_rsvp, rsvp_link) VALUES
('Taco Tuesday', '2025-08-05 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-08-12 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-08-19 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-08-26 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-09-02 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-09-09 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-09-16 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-09-23 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-09-30 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-10-07 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-10-14 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-10-21 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-10-28 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-11-04 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-11-11 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu'),
('Taco Tuesday', '2025-11-18 12:00:00+00', 'Specials', 'All-day tacos & Mexican beer specials. Choose from ground beef, shredded chicken, carnitas, or mahi mahi, and pair with a cold one. Every Tuesday.', 'on-site', 'published', false, '/menu');

-- Trivia Night events (6 PM local = 1 AM UTC next day)
INSERT INTO public.events (event_title, event_date, event_type, description, location, status, allow_rsvp, rsvp_link) VALUES
('Trivia Night', '2025-08-06 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-08-13 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-08-20 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-08-27 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-09-03 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-09-10 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-09-17 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-09-24 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-10-01 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-10-08 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-10-15 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-10-22 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-10-29 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-11-05 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-11-12 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/'),
('Trivia Night', '2025-11-19 01:00:00+00', 'Game Night', 'Flex those brain muscles every Tuesday at 6 PM—hosted by Last Call Trivia. Gather your crew and show off your smarts!', 'on-site', 'published', true, 'https://www.lastcalltrivia.com/');