// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqgdbufmokvrsydajdfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZ2RidWZtb2t2cnN5ZGFqZGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTczNjIsImV4cCI6MjA2MDQ5MzM2Mn0.aGckcRjor1nDLQq0Cc6mxJBN23iM3QCvljzZy5TTsGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);